name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building
      shell: pwsh
      run: | 
        make
        mkdir release
        cp helloos.img release
        
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: $(Get-Date)
        title: $(Get-Date) 自动发布
        prerelease: true
        files: |
          release/helloos.im
