name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        make
        mkdir release
        cp main release/main
    - name: Uploading
      uses: actions/upload-artifact@v1
      with:
        name: release_linux
        path: release
